### PR TITLE
replace timed mutex with mutex

### LINKED ISSUE #22: Remove timeout on mutex locks
throw an exception or log? 
should depend on some flag to throw or not to throw
connected to https://github.com/apigear-io/template-cpp14/issues/47 and  https://github.com/apigear-io/template-cpp14/issues/32

### PR DESCRIPTION
**Pull request by dorotaphanSiili**

### CODE REVIEW

File: src/olink/remoteregistry.cpp [hunk 1]
```diff
@@ -48,132 +41,100 @@ void RemoteRegistry::removeSource(const std::string& objectId)
...
-        return source;
-    }
-    else {
-        emitLog(LogLevel::Info, "RemoteRegistry.getObjectSource, registry is busy: " + objectId);
-    }
-    return {};
+    std::unique_lock<std::mutex> lock(m_entriesMutex);
+    auto found = m_entries.find(objectId);
+    auto source = found != m_entries.end() ? found->second.source : std::weak_ptr<IObjectSource>();
+    lock.unlock();
```
Comment (w4bremer) [inline src/olink/remoteregistry.cpp]: I think this unlock can be removed since it will be unlocked when leaving the scope?

File: src/olink/remoteregistry.cpp [hunk 2]
```diff
@@ -48,132 +41,100 @@ void RemoteRegistry::removeSource(const std::string& objectId)
...
-            lock.unlock();
-        }
-    }
-    else {
-        emitLog(LogLevel::Info, "RemoteRegistry.getNodes, registry is busy, no nodes searched for : " + objectId);
+        auto nodes = found->second.nodes;
+        lock.unlock();
+        return nodes;
+    } else {
+        lock.unlock();
```
Comment (w4bremer) [inline src/olink/remoteregistry.cpp]: this else/unlock can be completely removed

File: src/olink/remoteregistry.cpp [hunk 3]
```diff
@@ -48,132 +41,100 @@ void RemoteRegistry::removeSource(const std::string& objectId)
...
-            lock.unlock();
-            return nodes;
-        } else {
-            lock.unlock();
-        }
-    }
-    else {
-        emitLog(LogLevel::Info, "RemoteRegistry.getNodes, registry is busy, no nodes searched for : " + objectId);
+        auto nodes = found->second.nodes;
+        lock.unlock();
```
Comment (w4bremer) [inline src/olink/remoteregistry.cpp]: will be unlocked when leaving the scope -> remove

File: src/olink/remoteregistry.cpp [hunk 4]
```diff
@@ -48,132 +41,100 @@ void RemoteRegistry::removeSource(const std::string& objectId)
...
+
+        if (nodeIsAdded) {
+            ids.push_back(entry.first);
         }
-        lock.unlock();
-    }
-    else {
-        emitLog(LogLevel::Info, "RemoteRegistry.getObjectsId, registry is busy: no ids for node searched ");
     }
+    lock.unlock();
```
Comment (w4bremer) [inline src/olink/remoteregistry.cpp]: remove

File: src/olink/remoteregistry.cpp [hunk 5]
```diff
@@ -48,132 +41,100 @@ void RemoteRegistry::removeSource(const std::string& objectId)
...
+                                [node](auto element){ return !node.expired() && node.lock() == element.lock(); });
+        if (nodeInCollection != found->second.nodes.end()){
+            found->second.nodes.erase(nodeInCollection);
         }
-        lock.unlock();
-    }
-    else {
-        emitLog(LogLevel::Info, "RemoteRegistry.removeNodeFromSource, registry is busy node not removed! : " + objectId);
     }
+    lock.unlock();
```
Comment (w4bremer) [inline src/olink/remoteregistry.cpp]: remove

File: src/olink/remoteregistry.cpp [hunk 6]
```diff
@@ -48,132 +41,100 @@ void RemoteRegistry::removeSource(const std::string& objectId)
...
-        lock.unlock();
-    }
-    else {
-        emitLog(LogLevel::Info, "RemoteRegistry.removeEntry, registry is busy object not removed!: " + objectId);
+    std::unique_lock<std::mutex> lock(m_entriesMutex);
+    auto found = m_entries.find(objectId);
+    if (found != m_entries.end()) {
+        m_entries.erase(found);
     }
+    lock.unlock();
```
Comment (w4bremer) [inline src/olink/remoteregistry.cpp]: remove

File: src/olink/remoteregistry.cpp [hunk 7]
```diff
@@ -48,132 +41,100 @@ void RemoteRegistry::removeSource(const std::string& objectId)
...
+            != foundEntry->second.nodes.end();
+        if (!alreadyAdded)
         {
-            lock.unlock();
-            emitLog(LogLevel::Info, "RemoteRegistry.linkRemoteNode, node not added, no source for: " + objectId);
+            foundEntry->second.nodes.push_back(node);
         }
-    } else {
-        emitLog(LogLevel::Info, "RemoteRegistry.linkRemoteNode, add node request denied, registry is busy: " + objectId);
+        lock.unlock();
```
Comment (w4bremer) [inline src/olink/remoteregistry.cpp]: wrong scope? anyway remove

File: tests/test_remote_registry.cpp [hunk 8]
```diff
@@ -34,7 +34,7 @@ TEST_CASE("server registry simple tests without threads")
         REQUIRE(registry.getNodes(source1Id)[0].lock() == node1);
     }
 
-    SECTION("Node can be set to many sources")
+    SECTION("Node can be set many sources")
```
Comment (w4bremer) [inline tests/test_remote_registry.cpp]: why remove the `to`?

**Review by w4bremer — CHANGES_REQUESTED** [review]
Can be slightly simplified

**Review by w4bremer — APPROVED** [review]
